version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/magical-girl-gym-tracker-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/magical-girl-gym-tracker-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/magical-girl-gym-tracker-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/magical-girl-gym-tracker-backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  android-build:
    build:
      context: ./frontend/magical-girl-gym-tracker-frontend
      dockerfile: Dockerfile.android
    volumes:
      - ./frontend/magical-girl-gym-tracker-frontend:/app
      - android-build-cache:/root/.gradle
    profiles:
      - android

volumes:
  android-build-cache:

